CREATE DATABASE IF NOT EXISTS vibra CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vibra;

CREATE TABLE usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(80) NOT NULL,
 username VARCHAR(50) UNIQUE,
 email VARCHAR(150) NOT NULL UNIQUE,
 contraseña VARCHAR(255) NOT NULL,
 descripcion VARCHAR(255),
 foto_perfil VARCHAR(255),
 foto_portada VARCHAR(255),
 link_apoyo VARCHAR(500),
 fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE publicaciones (
 id INT AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT NOT NULL,
 imagen VARCHAR(255),
 video VARCHAR(255),
 tipo ENUM('imagen','video') NOT NULL DEFAULT 'imagen',
 descripcion VARCHAR(500),
 ubicacion VARCHAR(150),
 hashtags VARCHAR(500),
 musica_id INT NULL,
 fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE TABLE canciones (
 id INT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(120) NOT NULL,
 artista VARCHAR(120) NOT NULL,
 archivo VARCHAR(255) NOT NULL,
 portada VARCHAR(255),
 duracion INT,
 usuario_id INT NULL,
 fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);
CREATE TABLE likes (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, publicacion_id INT NOT NULL, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(usuario_id,publicacion_id), FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(publicacion_id) REFERENCES publicaciones(id) ON DELETE CASCADE);
CREATE TABLE comentarios (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, publicacion_id INT NOT NULL, comentario VARCHAR(500) NOT NULL, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(publicacion_id) REFERENCES publicaciones(id) ON DELETE CASCADE);
CREATE TABLE seguidores (id INT AUTO_INCREMENT PRIMARY KEY, seguidor_id INT NOT NULL, seguido_id INT NOT NULL, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(seguidor_id,seguido_id), FOREIGN KEY(seguidor_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(seguido_id) REFERENCES usuarios(id) ON DELETE CASCADE);
CREATE TABLE historias (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, archivo VARCHAR(255) NOT NULL, tipo ENUM('imagen','video') NOT NULL DEFAULT 'imagen', texto VARCHAR(255), fecha DATETIME DEFAULT CURRENT_TIMESTAMP, expira DATETIME NOT NULL, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE);
CREATE TABLE historia_vistas (id INT AUTO_INCREMENT PRIMARY KEY, historia_id INT NOT NULL, usuario_id INT NOT NULL, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(historia_id,usuario_id), FOREIGN KEY(historia_id) REFERENCES historias(id) ON DELETE CASCADE, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE);
CREATE TABLE guardados (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, publicacion_id INT NOT NULL, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(usuario_id,publicacion_id), FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(publicacion_id) REFERENCES publicaciones(id) ON DELETE CASCADE);
CREATE TABLE notificaciones (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, actor_id INT NULL, tipo VARCHAR(40) NOT NULL, publicacion_id INT NULL, texto VARCHAR(255) NOT NULL, leida TINYINT(1) DEFAULT 0, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(actor_id) REFERENCES usuarios(id) ON DELETE SET NULL, FOREIGN KEY(publicacion_id) REFERENCES publicaciones(id) ON DELETE CASCADE);
CREATE TABLE mensajes (id INT AUTO_INCREMENT PRIMARY KEY, remitente_id INT NOT NULL, destinatario_id INT NOT NULL, mensaje VARCHAR(1000) NOT NULL, leido TINYINT(1) DEFAULT 0, fecha DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(remitente_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(destinatario_id) REFERENCES usuarios(id) ON DELETE CASCADE);
CREATE TABLE apoyos (id INT AUTO_INCREMENT PRIMARY KEY, donante_id INT NOT NULL, creador_id INT NOT NULL, monto DECIMAL(10,2) NOT NULL, moneda VARCHAR(5) DEFAULT 'CLP', estado VARCHAR(30) DEFAULT 'pendiente', proveedor VARCHAR(50), referencia VARCHAR(150), fecha DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(donante_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(creador_id) REFERENCES usuarios(id) ON DELETE CASCADE);
CREATE TABLE reportes (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, publicacion_id INT NULL, usuario_reportado_id INT NULL, motivo VARCHAR(100) NOT NULL, detalle VARCHAR(500), fecha DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(publicacion_id) REFERENCES publicaciones(id) ON DELETE SET NULL, FOREIGN KEY(usuario_reportado_id) REFERENCES usuarios(id) ON DELETE SET NULL);
